### PR TITLE
feat: Database implementation

### PR DESCRIPTION
**Pull request by Stranger6667**
Hi! Sorry for the delay, here is a DB implementation. It additionally includes caching for hash values as it is in the Python implementation. The full version could be found in [this repo](https://github.com/Stranger6667/Hypothesis-rs/tree/master/crates/database/src)

Not sure, what will be the best way to integrate it though. Could you take a look please?

### CODE REVIEW

**Comment by Stranger6667** [comment]
Also, another missing thing - proper error handling. Currently, the bigger variety of errors is ignored in comparison to the Python version

**Comment by Rik-de-Kort** [comment]
Running `cargo test` gives me a panic because I don't have a folder named .minithesis-db, and the program didn't make it. Adding `fs::create_dir(path.as_ref())` on line 42 fixes it.

I think set and delete should pass  `&mut self` rather than `&self`. Also, why is `make_path` called in `get`? Shouldn't that return an error and do nothing to the cache if it's not already in there? I think this means we can also get rid of the refcell: have a method get_path which takes `&self` and returns the path if it's in the cache, and have a method `get_or_insert_path()` which takes `&mut self` (currently `make_path()`).
Because `get_path` returns an `Option` or `Result`, this will also give us the correct places to attach error handling.

Here's a gist with those changes: https://gist.github.com/Rik-de-Kort/23157140064dd09febad06396d738303

**Comment by Stranger6667** [comment]
Hm, probably I didn't adjust certain parts that I took from the Hypothesis implementation.

> I don't have a folder named .minithesis-db, and the program didn't make it.

In Hypothesis, it is checked on each call, which is probably doesn't fit here well. I'll change it according to your proposal.

> I think set and delete should pass &mut self rather than &self

Yep, makes sense; I missed that

> Also, why is make_path called in get? Shouldn't that return an error and do nothing to the cache if it's not already in there?

In this case, the test DB won't be persistent between test runs. E.g., if the cache is empty, the data still can be on the disk, saved in the previous test run. It also seems relevant to the `delete` call - we still need to try to remove the data on the disk. 

`RefCell` was the simplest way to implement caching, but probably for the minithesis implementation caching is not crucial at all - probably I can just drop it

**Comment by Rik-de-Kort** [comment]
Alright, I'll keep an eye out for the next commit and then we can probably merge :)

**Review by Rik-de-Kort — APPROVED** [review]
LGTM!

**Comment by Stranger6667** [comment]
Awesome! Thank you and sorry once again for the delay! :)

**Pull request merged**
